version: "3.3"
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ./src:/var/www/html