services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    networks:
      - lemp_network
  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www
    networks:
      - lemp_network
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
  mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:3306"
    volumes: 
      - ./data/mysql-data:/var/lib/mysql
    networks:
      - lemp_network
networks:
  lemp_network:
    driver: bridge